on:
  pull_request:
    types: [ labeled ]

jobs:
  quick-test:
    runs-on: ubuntu-latest
    steps:
      - name: Very quick test
        run: |
          echo "....................................................."
          echo ${{ github.event.label.name }}
          echo "....................................................."
